/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StartassessmentImport } from './routes/start_assessment'
import { Route as BillingImport } from './routes/billing'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StartassessmentRoute = StartassessmentImport.update({
  path: '/start_assessment',
  getParentRoute: () => rootRoute,
} as any)

const BillingRoute = BillingImport.update({
  path: '/billing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/billing': {
      preLoaderRoute: typeof BillingImport
      parentRoute: typeof rootRoute
    }
    '/start_assessment': {
      preLoaderRoute: typeof StartassessmentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  BillingRoute,
  StartassessmentRoute,
])

/* prettier-ignore-end */
